### ISSUE TITLE
summary(xpdb) doesn't report fully if file is control stream?

### ISSUE THREAD

**Issue by MikeKSmith** [UUPharmacometrics/xpose#10]
When using xpose_data with a NONMEM control stream, xpose_data doesn't seem to pick up and read any associated NONMEM output (.lst) file. So summary(xpdb) provides only minimal information. Is this expected behaviour? xpose_data / read_nm_model identifies the correct table files and .ext etc. but doesn't appear to parse the output file for use in summary(...).

When calling xpose_data using runno or providing an .lst (or equivalent) NONMEM output for the file argument the complete information is parsed from the output.

It might be good for xpose_data to search within the directory of file for output files with the same filename as the control stream if the ext = .mod.

**Comment by guiastrennec** [comment]
This is the expected behavior. We have made the decision to constrain the xpose summary to the file provided in `xpose_data`, and hence the summary is more extensive when an .lst file is provided (default). This decision was taken based on the facts that:
* output files are not necessarily named .lst 
* And that the name of the .lst and .mod are not necessarily the same if not generated with psn

*PS: Note that there is one exception when an. lst is provided but does not contain the model code xpose will attempt to read the associated .mod.*
