### ISSUE TITLE
`dv_preds_vs_idv` with faceting

### ISSUE THREAD

**Issue by sn248** [UUPharmacometrics/xpose#114]
Hi

I am trying to use the `dv_preds_vs_idv` with faceting, but I am not getting expected results. Function call without the faceting gives expected results, i.e.,

`dv_preds_vs_idv(xpdb, group = "ID")` generates a grid of plots (1 row and 3 columns) of `DV`, `IPRED` and `PRED` with independent variable `TIME`.

With `dv_preds_vs_idv(xpdb, group = "ID", facets = c("STUDY"))`, I expected a 12 plots (I have 4 studies), but I am getting only 4 plots (one for each study) with (I think) `DV`, `IPRED` and `PRED` combined in a single plot for each study. I reported the issue to my colleague Mike Smith also, who suggested to file a issue. 

I will be willing to provide code/data privately.

Last, but not the least, many thanks for the package!

**Comment by guiastrennec** [comment]
Hi,

xpose uses an internal facet called `'variable'` for all plots that have multiple panels by default such as `dv_preds_vs_idv()` or `eta_distrib()`, etc. So in order to get the plot that you want, simply add `'variable'` to your facets as follows:
`r dv_preds_vs_idv(xpdb, group = "ID", facets = c("variable", "STUDY"))`

Good luck

**Comment by sn248** [comment]
That works, thanks!!
