### ISSUE TITLE
Error when X=DV format is used in nonmem $input

### ISSUE THREAD

**Issue by Kagedal** [UUPharmacometrics/xpose#150]
If DV is defined in $input like this
$INPUT  ID PTNM TIME DV=X EVID....

To identify DV, I used this in xpose:
xpdb =xpdb %>%   set_var_types(dv="SLD",iwres = "CIWRES")

When running 
xpdb %>% dv_vs_ipred() 
I get Error: Discrete value supplied to continuous scale
Not very easy to understand this error message since the plot was not at all using any categorical data.

I think that X is appanded to the CATAB table and xpose gets confused when there is a continuous variable in that table.

**Comment by guiastrennec** [comment]
@Kagedal if DV is part of the catab table it is the expected behavior that it is considered a categorical covariate by xpose and thus converted to a factor thus the ggplot2 error message. I advise that you place DV in sdtab instead. If you do not want to rerun the model you can manually fix the DV class with:

```r
xpdb <- xpdb %>%
  mutate(DV = as.numeric(as.character(DV)))
```

Hope this help !

**Comment by guiastrennec** [comment]
Please reopen if the problem remains
