### ISSUE TITLE
Plotting a subset of data from PsN using vpc() and vpc_data()

### ISSUE THREAD

**Issue by justin-penz** [UUPharmacometrics/xpose#187]
Hi, is there a functionality to plot only a subset of data in a VPC, similar to, e.g., xpdb %>% filter(group = T) %>% ind_plots(page=1)?

Thank you,
Justin Penzenstadler

**Comment by guiastrennec** [comment]
Hi,

There are several possibilities:
1) If you do not use the `psn_folder` option you can as you pointed out use the `filter()` function on the `xpdb` to remove data that you do not wish to include in the VPC plot.
2) As you also pointed out you could play with the `page` argument, for example with `vpc(nrow = 1, ncol = 1, page = <selected pages>)` where `<selected pages>` is a vector of the panels you want to keep. But this would show you each panel on a different page.
3) You can use the `filter(.source = "special")` functionality to edit the vpc data created with `vpc_data()` in the `xpdb` before calling vpc(). This will give you the result that you want but unfortunately it's a but more cumbersome to setup because you need to filter out the simulation summary, the observation summary and the observed data. You can see an example on how to edit the vpc_data [here](https://github.com/UUPharmacometrics/xpose/issues/110).

Hope it helps.
Ben

**Comment by justin-penz** [comment]
Thank you Ben.  This was very helpful.  
Best, Justin
