### ISSUE TITLE
issues importing xpdb with both sim and obs tables

### ISSUE THREAD

**Issue by ftuhin2828** [UUPharmacometrics/xpose#216]
When I import the xpdb object from estimation run, it cannot find the simulation tables. When I import xpdb object from simulations run, it cannot find the observed table. How do I get the xpdb imported from nonmem output lst file with both estimation and simulation tables so I can create vpc plots? Thanks in advance!

Fazlur

**Comment by guiastrennec** [comment]
Hello, currently the only way to have both estimation and simulation tables simultaneously in the xpdb object is to have a single run with 2 $PROBLEM as exemplified [here](https://github.com/UUPharmacometrics/xpose/blob/master/inst/extdata/run001.mod). In xpose v0.5 I plan to add the option to combine xpdb together e.g. `c(xpdb_est, xpdb_sim)`. 

Of note, if your VPC was created with PsN you can instead of the 2 $PROBLEM approach use the argument `psn_folder` in `vpc_data`
