### ISSUE TITLE
ETA distributions in nlmixr

### ISSUE THREAD

**Issue by kestrel99** [UUPharmacometrics/xpose#75]
Hi,

I'm having an issue with plotting ETAs generated by nlmixr using `eta_distrib`:
```
Error in mutate_impl(.data, dots) : 
  Column `variable` must be length 3 (the group size) or one, not 36
```
There are 3 ETAs in the model, and input to the function is an Xpose data object created using the `xpose_data_nlmixr` function in [xpose.nlmixr](https://github.com/nlmixrdevelopment/xpose.nlmixr). The whole example can be recreated using the example code at [https://github.com/nlmixrdevelopment/nlmixr/blob/master/vignettes/running_nlmixr.Rmd](https://github.com/nlmixrdevelopment/nlmixr/blob/master/vignettes/running_nlmixr.Rmd).

I was able to trace the issue back to a call to `fetch_data` in `xplot_distrib`, but I got stuck at that point. I'm not enough of a dplyr expert to figure out what's happening: do you have any insights? It should be a really simple thing to do, and as far as I can see the Xpose data object created by `xpose_data_nlmixr` is identical to an equivalent created by `xpose_data`... or am I missing something obvious?

Here's the offending Xpose data object: 
[nlmixrFit.zip](https://github.com/UUPharmacometrics/xpose/files/1503790/nlmixrFit.zip)

**Comment by guiastrennec** [comment]
The problem comes from the post processing function given to fetch_data. This function is in charge of nicely formatting and ordering the ETAs from NONMEM runs. I will add a fix on the dev branch now.

Also, I was playing around a bit with the nlmixr xpdb, good job with it seems to work nicely. In the future,  I will aim to improve the integration of additional tools as I realized it may have in some cases been too focused on NONMEM.

**Comment by guiastrennec** [comment]
Fixed in #77

**Comment by kestrel99** [comment]
`eta_distrib()` still does not appear to be working...

> eta_distrib(xp)
```
Adding missing grouping variables: `ID`
Dropped fixed variables ID.
Using data from $prob no.1
Removing duplicated rows based on: ID, variable
Tidying data by ID, TIME, DV, IPRED, PRED ... and 7 more variables
Error in mutate_impl(.data, dots) : 
  Column `variable` must be length 3 (the group size) or one, not 36
```

**Comment by guiastrennec** [comment]
@kestrel99 the fix is working for me using the file you sent me. Please make sure the you used the **dev branch** of xpose when you updated i.e. `devtools::install_github('UUPharmacometrics/xpose@dev')`. I have changed the version to from 0.4.0  to 0.4.1 to make it easier for you to check it you got the latest update.
